### ISSUE TITLE
EXTRACT throws an error if avg_cell_radius is empty or a string

### ISSUE THREAD

**Issue by bahanonu** [schnitzer-lab/EXTRACT-public#23]
@fatihdinc Can EXTRACT check that `avg_cell_radius` is not an empty vector or string/character? Else MATLAB throws the below error at https://github.com/schnitzer-lab/EXTRACT-public/blob/master/EXTRACT/helper_functions/spatial_bandpass.m#L52.

```Matlab
Error using  / 
Matrix dimensions must agree.
```

Potentially in `extractor.m` at lines https://github.com/schnitzer-lab/EXTRACT-public/blob/master/EXTRACT/solvers/extractor.m#L16-L18 this check could also occur and throw an error to make it explicit to users, similar to if `avg_cell_radius` option is not present.

**Comment by fatihdinc** [comment]
Thank you Biafra for bringing this into my attention. This check is now being made, please let me know if the issue still exists for you or feel free to close this issue!
