### ISSUE TITLE
[general help on improving cell extraction] 

### ISSUE THREAD

**Issue by sg-s** [schnitzer-lab/EXTRACT-public#30]
Hello, ran EXTRACT on some 1-p data and I am generally unhappy with the cells extracted. some screenshots below. I would greatly appreciate any help in improving cell extraction. I ran this on all defaults. Which parameters should I change to:

- get rid of clear non-cells (weird footprints, monotonically decreasing cells)
- improve SNR
- 

<img width="1063" alt="Screenshot 2022-11-21 at 11 36 06 AM" src="https://user-images.githubusercontent.com/6005346/203109923-9155e8d4-654b-4dde-ac24-34e7d6369da9.png">

<img width="1069" alt="Screenshot 2022-11-21 at 11 37 06 AM" src="https://user-images.githubusercontent.com/6005346/203110152-6acac122-4f63-44bc-9bc2-0eb2ad2094da.png">

In my opinion this is the "best" cell in this data, which isn't great:

<img width="1048" alt="Screenshot 2022-11-21 at 11 38 07 AM" src="https://user-images.githubusercontent.com/6005346/203110355-8fcbee04-89a0-4f70-a60c-8c5c885bacc3.png">

**Comment by fatihdinc** [comment]
Would you mind sending over the movie through my email? Happy to give it a look!

**Comment by sg-s** [comment]
thank you! will send

**Comment by fatihdinc** [comment]
Let's follow up on the email. It seems the movie is over-processed, so we will try again with the raw, only motion corrected, movie!
