### ISSUE TITLE
inconsistencies b/w docs and code

### ISSUE THREAD

**Issue by sg-s** [schnitzer-lab/EXTRACT-public#32]
in [this file](https://github.com/schnitzer-lab/EXTRACT-public/tree/master/Learning%20materials/Lecture%20Tutorials/Tutorial%202%20-%20Understanding%20hyperparameters), we find the following:

> trace_output_option: EXTRACT has two options for trace output: 'raw' and 'nonneg'. 'nonneg' outputs only the signal portion of the trace, consistent with the fundamental assumptions of EXTRACT. 'raw' outputs signal + noise. Default: 'nonneg'.

However, when we look at the default config, we find:

```matlab
>> config = get_defaults([]);
>> config.trace_output_option
ans =
    'baseline_adjusted'
```

which is not referred to in the docs

**Comment by fatihdinc** [comment]
Thanks! I am in the process of re-writing the full documentation, and will add a user manual soon.
