### ISSUE TITLE
Request: create version 1.0.2

### ISSUE THREAD

**Issue by stevewds** [schnitzer-lab/EXTRACT-public#43]
Hi Fatih - 

When you have a chance, can you please create a new version, maybe 1.0.2? This will update the files on Matlab File Exchange. Then, I will be able to link to a viewer of the newcomer tutorial (so that someone can see the output of the Matlab live script even if they are just in a web browser).

To do this, if you are on the Code tap, you can click "Releases" and make a new release.

There's no rush.

Thanks
Steve

**Comment by fatihdinc** [comment]
Done, thank you!
