### ISSUE TITLE
Instructions for the Use of the config.crop_circular Parameter

### ISSUE THREAD

**Issue by 1re2turn1** [schnitzer-lab/EXTRACT-public#58]
Hi EXTRACT team,

Thank you very much for developing such an excellent program like EXTRACT! 

I'd like to ask if there is any instruction on the use of the parameter config.crop_circular (When I run extractor(M, config) with the default parameters, the circular field of view boundary is often wrongly extracted as a cell. I think this parameter might help solve this problem). However, after I set config.crop_circular = 1 and run the program, Matlab reported an error (as shown in the figure below).
![Screenshot 2024-11-23 123903](https://github.com/user-attachments/assets/8f281c12-3740-4b07-b6a3-60e130829c2c)
![image](https://github.com/user-attachments/assets/f1bbb740-4b13-4e41-9c47-8132dfc4f86b)

Thank you in advance for the help.

**Comment by fatihdinc** [comment]
Hello! Thank you for reaching out. I realized there was a small bug with the code. Could you please pull and try again? Thank you!

**Comment by 1re2turn1** [comment]
> Hello! Thank you for reaching out. I realized there was a small bug with the code. Could you please pull and try again? Thank you!

Thank you very much for your help! I updated the code and re-ran the previous code, and now it is possible to do the cell_find session, but there still seems to be a minor problem (the command line shows noise std=0, minimum magnitude=0 ?)
![image](https://github.com/user-attachments/assets/a2a41016-6428-41b3-9a69-66963f9d15fb)

**Comment by fatihdinc** [comment]
This is surprising. Would you like to send an example movie over to our email: extractneurons@gmail.com ?

**Comment by 1re2turn1** [comment]
> This is surprising. Would you like to send an example movie over to our email: [extractneurons@gmail.com](mailto:extractneurons@gmail.com) ?

Thanks for your help! The email has been sent, please check

**Comment by fatihdinc** [comment]
This was an interesting bug. Thank you for the email. It should be fixed now, please double check and feel free to reopen the issue. Good luck!
